### ISSUE TITLE
ajax return of post resulting in http 500 error.

### ISSUE THREAD

**Issue by proseLA** [marco-pm/zencart_instantsearchplus#2]
i have a vanilla dev box running v158.  i am getting a 500 error on the post.  see:

![image](https://user-images.githubusercontent.com/1095136/126512355-7729a66b-d09c-402c-8e8f-0821e5907b41.png)

sorry my javascript/jquery debugging is not better.

i tried this on on a v157c dev box that i have running as well.  i am getting an error at the same point, although in this case, the return is a 400 (Bad Request).  on that box, the i'm running jquery 1.11.1.

the out of the box vanilla v158 runs jquery 3.5.1.

would love to help with this plugin, as i see good potential.

best.

**Comment by marco-pm** [comment]
For the v157c I think the problem may be the old jquery version. 

For both environments (157c and 158) please let me know:
- PHP version on the server
- the contents of the debug log(s) (under the `/logs` directory)
- if the error arises for every search or only for some searches (and in this case, which keywords)

**Comment by proseLA** [comment]
actually, i made a small error in the 157c install.  i had the `zcAjaxInstantSearch.php` in `includes/classes` as opposed to `includes/classes/ajax`.  moving it there provides the same http response.  and now, of course, i am getting debug files (previously not)

```
PHP Parse error: syntax error, unexpected 'fn' (T_STRING), expecting :: (T_PAAMAYIM_NEKUDOTAYIM) in /var/www/zcdev/includes/classes/ajax/zcAjaxInstantSearch.php on line 95.
```

php version is 7.3.27

happens on all searches.

**Comment by proseLA** [comment]
looks like it might be a minimum of php 7.4.  i will confirm....

**Comment by proseLA** [comment]
yeah, that's confirmed (and right on your readme).  will not work without code changes.

my next issue will be better.

**Comment by proseLA** [comment]
changing this:
https://github.com/marco-pm/zencart_instantsearchplus/blob/b10c7f68e78e20907c1081344d29a519d25cd272/INSTALL/includes/classes/ajax/zcAjaxInstantSearch.php#L95-L99

to:
```
                usort($results, static function($prod1, $prod2) {
	                [$prod2['mtch'], $prod1['fsum'], $prod2['views']]
	                <=>
	                [$prod1['mtch'], $prod2['fsum'], $prod1['views']];
                    }
                );
```
would make it compatible with php7.3.

considering one has to add sury repos to a debian install to get to php7.4, i would think that making it 7.3 compatible is not a bad idea.
