### ISSUE TITLE
width always coming up as 0...

### ISSUE THREAD

**Issue by proseLA** [marco-pm/zencart_instantsearchplus#3]
marco,
i am digging what you did.  i'm having a problem in that no matter how i play around with the positioning, i am always getting the width setting at 0px as such:

```
<div class="resultsContainer" style="width: 0px; display: none; left: 1615.8px; top: 243.8px;">
```

any clues as to where jquery might be changing that and how to override that?

in you prefer, i can open up a few more issues, else i can make a few observations here:

- i think a notifier prior to executing the sql with the ability to override the sql statement would be great.  `products_status <> 0` is not enough for some of my clients.
- while it is another database call, i prefer to use this (i change this function): `$productName = zen_get_products_name($dbProduct['products_id']);`  my products name is a combination of a couple of attributes.

needless to say, i can get around them, but i prefer not to mess with the core code of this plugin.

any help on where that width gets set is appreciated.

best.

**Comment by marco-pm** [comment]
I'll look into this.

Please open a separate issue for every note/request 😊
